Algoritmo "media-ponderada-do-aluno"

Var
  disciplina : caractere
  prova : real
  nota : vetor[1..3] de inteiro
  peso : real
  
Inicio
  Escreval("Disciplina: ")
  leia(disciplina)
  Escreval("Inserir Notas?")
  Escreval("DIGITE 1 PARA SIM")
  Escreval("DIGITE 2 PARA NÃO?")
  leia(prova)
  
  escolha prova
    caso 1
      Escreval("Inserir Notas?")
      Escreval("DIGITE 1 PARA SIM")
      Escreval("DIGITE 2 PARA NÃO?")
      leia(prova)


  fimescolha

Fimalgoritmo

