Algoritmo "Exercici4-finalizar"

Var
// Seção de Declarações das variáveis
   data1 : inteiro
   data2 : inteiro
   idade1 : inteiro
   idade2 : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Usuario 1 Data de Nascimento")
   leia (data1)
   escreval ("Usuario 2 Data de Nascimento")
   leia (data2)

   idade1 <- 2020 - data1
   idade2 <- 2020 - data2

   Escreval ("Usuario 1 idade: ",idade1)
   Escreval ("Usuario 2 idade: ",idade2)

Fimalgoritmo